In [ ]:
import pandas as pd

In [ ]:
acd1 = pd.read_csv('./위반유형별교통사고유형.csv',
                   encoding = 'utf-8')
acd1

,Unnamed: 0,년도,시도,지자체,위반유형,차량종류,발생건수,대형사고,중대사고-여객,중대사고-화물,사망자수,치사율(%)
0,0,2018,서울,강동구,중앙선침범,승용,22.0,0.0,0,0,0.0,0.0
1,1,2018,서울,강동구,중앙선침범,승합,1.0,0.0,0,0,0.0,0.0
2,2,2018,서울,강동구,중앙선침범,화물,4.0,0.0,0,0,0.0,0.0
3,3,2018,서울,강동구,중앙선침범,이륜,3.0,0.0,0,0,0.0,0.0
4,4,2018,서울,강동구,중앙선침범,자전거,4.0,0.0,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
5300,5300,2021,서울,강남구,차로위반,승용,40.0,0.0,0,0,0.0,0.0
5301,5301,2021,서울,강남구,차로위반,승합,4.0,0.0,0,0,0.0,0.0
5302,5302,2021,서울,강남구,차로위반,특수,1.0,0.0,0,0,0.0,0.0
5303,5303,2021,서울,강남구,차로위반,이륜,5.0,0.0,0,0,0.0,0.0
5304,5304,2021,서울,강남구,차로위반,기타,2.0,0.0,0,0,0.0,0.0

In [ ]:
acd2 = pd.read_excel('./age_result.xlsx')
acd2.to_csv('연령별교통사고유형.csv', index = True, sep = ',',
            encoding = 'utf-8-sig')
acd2

,Unnamed: 0,년도,시도,지자체,연령대,차량종류,발생건수,대형사고,중대사고-여객(건),중대사고-화물(건),사망자수,치사율(%)
0,1,2018,서울,강남구,20대 미만,승용,9,0,0,0,0,0.00
1,2,2018,서울,강남구,20대 미만,이륜,10,0,0,0,0,0.00
2,3,2018,서울,강남구,20대 미만,원동기,1,0,0,0,0,0.00
3,4,2018,서울,강남구,20대 미만,자전거,15,0,0,0,0,0.00
4,6,2018,서울,강남구,20대,승용,321,0,0,0,1,0.31
...,...,...,...,...,...,...,...,...,...,...,...,...
4540,47,2021,서울,노원구,60대 이상,건설기계,4,0,0,0,0,0.00
4541,48,2021,서울,노원구,60대 이상,기타,2,0,0,0,0,0.00
4542,50,2021,서울,노원구,알수없음,이륜,1,0,0,0,0,0.00
4543,51,2021,서울,노원구,알수없음,자전거,3,0,0,0,0,0.00
4544,52,2021,서울,노원구,알수없음,기타,16,0,0,0,0,0.00

In [ ]:
acd3 = pd.read_csv('./sex_data.csv'
                   , encoding = 'cp949')
acd3

,Unnamed: 0,year,구,성별,차량종류,발생건수,대형사고,중대사고-여객,중대사고-화물,사망자수,치사율
0,0,2018,강동구,남성,승용,683,0,0,0,5,0.73
1,1,2018,강동구,남성,승합,106,0,0,0,1,0.94
2,2,2018,강동구,남성,화물,134,0,0,9,1,0.75
3,3,2018,강동구,남성,특수,7,0,0,0,0,0.00
4,4,2018,강동구,남성,이륜,90,0,0,0,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...
1868,1868,2021,강남구,알수없음,이륜,1,0,0,0,0,0.00
1869,1869,2021,강남구,알수없음,원동기,1,0,0,0,0,0.00
1870,1870,2021,강남구,알수없음,자전거,1,0,0,0,0,0.00
1871,1871,2021,강남구,알수없음,개인형이동수단(PM),1,0,0,0,0,0.00
1872,1872,2021,강남구,알수없음,기타,84,0,0,0,0,0.00

In [ ]:
acd4 = pd.read_csv('./weather_data.csv'
                   , encoding = 'cp949')
acd4

,Unnamed: 0,year,구,기상상태,차량종류,발생건수,대형사고,중대사고-여객,중대사고-화물,사망자수,치사율
0,0,2018,강동구,맑음,승용,792,0,0,0,7,0.88
1,1,2018,강동구,맑음,승합,98,0,0,0,0,0.00
2,2,2018,강동구,맑음,화물,118,0,0,8,1,0.85
3,3,2018,강동구,맑음,특수,7,0,0,0,0,0.00
4,4,2018,강동구,맑음,이륜,83,0,0,0,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...
2879,2879,2021,강남구,기타,이륜,17,0,0,0,0,0.00
2880,2880,2021,강남구,기타,원동기,1,0,0,0,0,0.00
2881,2881,2021,강남구,기타,자전거,3,0,0,0,0,0.00
2882,2882,2021,강남구,기타,개인형이동수단(PM),5,0,0,0,0,0.00
2883,2883,2021,강남구,기타,기타,9,0,0,0,0,0.00

#### 열 이름 일치시키기

In [ ]:
acd3.rename(columns = {'year':'년도', '구':'지자체'}, inplace = True)
acd4.rename(columns = {'year':'년도', '구':'지자체'}, inplace = True)

### 위반유형별 사고 데이터

In [ ]:
acd1.drop(acd1.columns[0], axis = 1, inplace = True)
acd1 = acd1[acd1['차량종류'] == '개인형이동수단(PM)']
acd1 = acd1[['년도', '지자체', '위반유형', '발생건수', '사망자수']]
acd1

        년도   지자체     위반유형  발생건수  사망자수
36    2018   강동구  안전운전불이행   2.0   0.0
69    2018  동대문구     신호위반   2.0   0.0
78    2018  동대문구  안전거리미확보   1.0   0.0
94    2018  동대문구  안전운전불이행   2.0   0.0
145   2018   동작구  안전운전불이행   1.0   0.0
...    ...   ...      ...   ...   ...
5213  2021   도봉구     신호위반   2.0   0.0
5229  2021   도봉구  안전운전불이행   1.0   0.0
5255  2021   강남구    중앙선침범   2.0   0.0
5262  2021   강남구     신호위반   6.0   0.0
5286  2021   강남구  안전운전불이행  50.0   0.0

[233 rows x 5 columns]

In [ ]:
types = acd1.위반유형.unique()
len(types)

9

In [ ]:
gu = acd1.지자체.unique()
len(gu)

25

In [ ]:
acd1.columns

Index(['년도', '지자체', '위반유형', '발생건수', '사망자수'], dtype='object')

#### 구별 유형별 전체년도 사고건수 구하기

In [ ]:
acd1_df = pd.DataFrame([], columns=['지자체', '위반유형', '발생건수'])
i = 0
for t in types:
    for g in gu:
        acd1_df.loc[i] = [g, t, acd1[(acd1['위반유형'] == t) & (acd1['지자체'] == g)].발생건수.sum()]
        i += 1

In [ ]:
acd1_df

      지자체       위반유형  발생건수
0     강동구    안전운전불이행  16.0
1    동대문구    안전운전불이행  19.0
2     동작구    안전운전불이행  20.0
3     마포구    안전운전불이행  53.0
4     서초구    안전운전불이행  40.0
..    ...        ...   ...
220  서대문구  직진우회전진행방해   0.0
221   송파구  직진우회전진행방해   0.0
222   양천구  직진우회전진행방해   0.0
223    중구  직진우회전진행방해   0.0
224   금천구  직진우회전진행방해   1.0

[225 rows x 3 columns]

In [ ]:
acd1_df.to_csv('./위반유형별 교통사고 전처리 데이터.csv', encoding='cp949')

### 연령대별 사고 데이터

In [ ]:
acd2.drop(acd2.columns[0], axis = 1, inplace = True)
acd2 = acd2[acd2['차량종류'] == '개인형이동수단(PM)']
acd2 = acd2[['년도', '지자체', '연령대', '발생건수', '사망자수']]
acd2

        년도   지자체     연령대  발생건수  사망자수
12    2018   강남구     20대     2     0
21    2018   강남구     30대     1     0
86    2018   도봉구  60대 이상     1     0
101   2018  동대문구     20대     2     0
116   2018  동대문구     40대     3     0
...    ...   ...     ...   ...   ...
4473  2021   금천구     30대     1     0
4480  2021   금천구     40대     1     0
4503  2021   노원구  20대 미만     7     1
4510  2021   노원구     20대     9     0
4519  2021   노원구     30대     2     0

[310 rows x 5 columns]

In [ ]:
types = acd2.연령대.unique()
len(types)

7

#### 구별 유형별 전체년도 사고건수 구하기

In [ ]:
acd2_df = pd.DataFrame([], columns=['지자체', '연령대', '발생건수'])
i = 0
for t in types:
    for g in gu:
        acd2_df.loc[i] = [g, t, acd2[(acd2['연령대'] == t) & (acd2['지자체'] == g)].발생건수.sum()]
        i += 1

In [ ]:
acd2_df

      지자체   연령대  발생건수
0     강동구   20대     7
1    동대문구   20대    14
2     동작구   20대    22
3     마포구   20대    42
4     서초구   20대    35
..    ...   ...   ...
170  서대문구  알수없음     0
171   송파구  알수없음     0
172   양천구  알수없음     0
173    중구  알수없음     0
174   금천구  알수없음     0

[175 rows x 3 columns]

In [ ]:
acd2_df.to_csv('./연령별 교통사고 전처리 데이터.csv', encoding='cp949')

### 성별 사고 데이터

In [ ]:
acd3.drop(acd3.columns[0], axis = 1, inplace = True)
acd3 = acd3[acd3['차량종류'] == '개인형이동수단(PM)']
acd3 = acd3[['년도', '지자체', '성별', '발생건수', '사망자수']]
types = acd2.연령대.unique()
len(types)

acd2_df = pd.DataFrame([], columns=['지자체', '연령대', '발생건수'])
i = 0
for t in types:
    for g in gu:
        acd2_df.loc[i] = [g, t, acd2[(acd2['연령대'] == t) & (acd2['지자체'] == g)].발생건수.sum()]
        i += 1

acd3

        년도   지자체    성별  발생건수  사망자수
8     2018   강동구    남성     2     0
26    2018  동대문구    남성     3     0
34    2018  동대문구    여성     2     0
47    2018   동작구    남성     1     0
63    2018   마포구    남성     3     0
...    ...   ...   ...   ...   ...
1839  2021   도봉구    남성     1     0
1845  2021   도봉구    여성     2     0
1857  2021   강남구    남성    57     0
1865  2021   강남구    여성    23     0
1871  2021   강남구  알수없음     1     0

[169 rows x 5 columns]

In [ ]:
types = acd3.성별.unique()
len(types)

3

#### 구별 유형별 전체년도 사고건수 구하기

In [ ]:
acd3_df = pd.DataFrame([], columns=['지자체', '성별', '발생건수'])
i = 0
for t in types:
    for g in gu:
        acd3_df.loc[i] = [g, t, acd3[(acd3['성별'] == t) & (acd3['지자체'] == g)].발생건수.sum()]
        i += 1

In [ ]:
acd3_df

     지자체    성별  발생건수
0    강동구    남성    16
1   동대문구    남성    26
2    동작구    남성    29
3    마포구    남성    52
4    서초구    남성    60
..   ...   ...   ...
70  서대문구  알수없음     0
71   송파구  알수없음     0
72   양천구  알수없음     0
73    중구  알수없음     0
74   금천구  알수없음     0

[75 rows x 3 columns]

In [ ]:
acd3_df.to_csv('./성별 교통사고 전처리 데이터.csv', encoding='cp949')

### 기상상태별 사고 데이터

In [ ]:
acd4.drop(acd4.columns[0], axis = 1, inplace = True)
acd4 = acd4[acd4['차량종류'] == '개인형이동수단(PM)']
acd4 = acd4[['년도', '지자체', '기상상태', '발생건수', '사망자수']]
acd4

        년도   지자체 기상상태  발생건수  사망자수
8     2018   강동구   맑음     2     0
39    2018  동대문구   맑음     5     0
72    2018   동작구   맑음     1     0
102   2018   마포구   맑음     4     0
154   2018   서초구   맑음     1     0
...    ...   ...  ...   ...   ...
2823  2021   도봉구   맑음     3     0
2854  2021   강남구   맑음    71     0
2862  2021   강남구   흐림     3     0
2870  2021   강남구    비     2     0
2882  2021   강남구   기타     5     0

[147 rows x 5 columns]

In [ ]:
types = acd4.기상상태.unique()
len(types)

5

#### 구별 유형별 전체년도 사고건수 구하기

In [ ]:
acd4_df = pd.DataFrame([], columns=['지자체', '기상상태', '발생건수'])
i = 0
for t in types:
    for g in gu:
        acd4_df.loc[i] = [g, t, acd4[(acd4['기상상태'] == t) & (acd4['지자체'] == g)].발생건수.sum()]
        i += 1

In [ ]:
acd4_df

      지자체 기상상태  발생건수
0     강동구   맑음    21
1    동대문구   맑음    29
2     동작구   맑음    33
3     마포구   맑음    66
4     서초구   맑음    70
..    ...  ...   ...
120  서대문구    눈     0
121   송파구    눈     0
122   양천구    눈     0
123    중구    눈     0
124   금천구    눈     0

[125 rows x 3 columns]

In [ ]:
acd4_df.to_csv('./기상상태별 교통사고 전처리 데이터.csv', encoding='cp949')